services:
  frontend:
    build:
      context: ./portfolio
      target: build
    volumes:
      - ./portfolio:/app
    tty: true
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=dev
    working_dir: /app
    command: ["npm", "run", "dev"]

  nginx:
    build:
      context: nginx
    logging:
      driver: none
    restart: always
    tty: true
    ports:
      - "80:80"
    depends_on:
      - frontend
