ingress:
  rules:
  - component:
      name: ashtonportfolio
    match:
      path:
        prefix: /
name: ashtonportfolio
region: nyc
services:
- dockerfile_path: portfolio/Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: ahonnecke/portfolio
  http_port: 3000
  source_dir: portfolio
  instance_count: 1
  instance_size_slug: basic-xxs
  name: ashtonportfolio
