name: ashtonportfolio
region: nyc
services:
- dockerfile_path: portfolio/Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: ahonnecke/portfolio
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: ashtonportfolio
  routes:
  - path: /
  source_dir: /
