name: Build, Push, Deploy
on:
  release:
    types: [created, published]
  push:
    branches: [main]
  workflow_call:
jobs:
  # lint:
  #   uses: ./.github/workflows/lint.yaml
  # clean_install_test:
  #   uses: ./.github/workflows/clean_install_test.yaml
  #   needs: lint
  build_push:
    name: build_push
    # needs: [clean_install_test]
    if: github.event_name == 'release' || github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      DO_APP_ID: dc34af0e-170f-4861-94ee-a385ce011ea2
      RELEASE_TAG: ${{ github.event_name == 'release' && github.event.release.tag_name || format('commit-{0}', github.sha) }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "npm"
          cache-dependency-path: portfolio/package-lock.json
      - name: Build frontend
        working-directory: ./portfolio
        run: |
          npm ci
          npm run build
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      - name: Create deployment
        run: |
          # Create deployment without updating app spec
          doctl apps create-deployment $DO_APP_ID --wait
