name: Build, Push, Deploy
on:
  release:
    types: [created, published]
  push:
    branches: [main]
  workflow_call:
jobs:
  # lint:
  #   uses: ./.github/workflows/lint.yaml
  # clean_install_test:
  #   uses: ./.github/workflows/clean_install_test.yaml
  #   needs: lint
  build_push:
    name: build_push
    needs: [clean_install_test]
    if: github.event_name == 'release' || github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      DO_APP_ID: ${{ secrets.DIGITALOCEAN_APP_ID }}
      RELEASE_TAG: ${{ github.event_name == 'release' && github.event.release.tag_name || format('commit-{0}', github.sha) }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "npm"
          cache-dependency-path: portfolio/package-lock.json
      - name: Build frontend
        working-directory: ./portfolio
        run: |
          npm ci
          npm run build
      - name: Build Docker image for deploy
        run: |
          docker build -f portfolio/Dockerfile -t portfolio/ashtonportfolio ./portfolio
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: |
          docker tag portfolio/ashtonportfolio registry.digitalocean.com/beampockets/ashtonportfolio:${{ env.RELEASE_TAG }}
          docker tag portfolio/ashtonportfolio registry.digitalocean.com/beampockets/ashtonportfolio:latest
      - name: Push image to DO Container Registry
        run: |
          docker push registry.digitalocean.com/beampockets/ashtonportfolio:${{ env.RELEASE_TAG }}
          docker push registry.digitalocean.com/beampockets/ashtonportfolio:latest
      - name: Create deployment
        run: doctl apps create-deployment $DO_APP_ID
